version: '3'
services:
  phpdb:
    build: .
    volumes:
      - ./:/var/www
      - ./.docker/nginx/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - phpdb-mysql
      - phpdb-mssql
      - phpdb-redis

  phpdb-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_phpdb
      MYSQL_ROOT_PASSWORD: toor

  phpdb-mssql:
    image: "microsoft/mssql-server-linux"
    volumes:
      - "./.docker/dbserver:/var/opt/mssql"
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Asterix2108@
      - ACCEPT_EULA=Y

  phpdb-nginx:
    build: ./.docker/nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - phpdb

  phpdb-redis:
    image: redis:alpine
    expose:
      - 6379